import json
import os
import re
import unicodedata
from contextlib import contextmanager
from datetime import datetime, timezone
from pathlib import Path

import psycopg
from flask import current_app, g, has_app_context
from psycopg.rows import dict_row
from psycopg.types.json import Jsonb

BIND_LIMIT = 500
SQLITE_BIND_LIMIT = BIND_LIMIT

_COMBINING_CLASS = f"[{chr(0x300)}-{chr(0x36F)}]"
_ZW_CLASS = f"[{chr(0x200B)}{chr(0x200C)}{chr(0x200D)}{chr(0xFEFF)}]"

SCHEMA_STATEMENTS = [
    """
    CREATE TABLE IF NOT EXISTS config (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        process_id INTEGER,
        data JSONB
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS emp (
        id INTEGER PRIMARY KEY,
        name TEXT,
        pbb TEXT,
        pba TEXT
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS oders (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        co TEXT,
        emp_id INTEGER,
        process_id INTEGER,
        note TEXT,
        created_at TIMESTAMPTZ DEFAULT now()
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS process (
        id INTEGER PRIMARY KEY,
        name TEXT
    )
    """,
    "CREATE UNIQUE INDEX IF NOT EXISTS oders_co_process_uq ON oders (co, process_id)",
    "CREATE UNIQUE INDEX IF NOT EXISTS process_id_uq ON process (id)",
    "CREATE INDEX IF NOT EXISTS oders_emp_id_idx ON oders (emp_id)",
    "CREATE INDEX IF NOT EXISTS oders_process_id_idx ON oders (process_id)",
    "CREATE INDEX IF NOT EXISTS oders_created_at_idx ON oders (created_at)",
    "CREATE INDEX IF NOT EXISTS config_process_id_idx ON config (process_id)",
]

SQL_FUNCTIONS = [
    f"""
    CREATE OR REPLACE FUNCTION om_fold(value text)
    RETURNS text
    LANGUAGE sql
    IMMUTABLE
    AS $$
      SELECT btrim(lower(replace(replace(
        regexp_replace(
          regexp_replace(
            normalize(normalize(coalesce(value, ''), NFKC), NFD),
            '{_COMBINING_CLASS}',
            '',
            'g'
          ),
          '{_ZW_CLASS}',
          '',
          'g'
        ),
        'đ', 'd'), 'Đ', 'd')))
    $$
    """,
    """
    CREATE OR REPLACE FUNCTION om_compact(value text)
    RETURNS text
    LANGUAGE sql
    IMMUTABLE
    AS $$
      SELECT regexp_replace(om_fold(value), '[^a-z0-9]+', '', 'g')
    $$
    """,
    """
    CREATE OR REPLACE FUNCTION instr(haystack text, needle text)
    RETURNS integer
    LANGUAGE sql
    IMMUTABLE
    AS $$
      SELECT strpos(coalesce(haystack, ''), coalesce(needle, ''))
    $$
    """,
    """
    CREATE OR REPLACE FUNCTION ifnull(a text, b text)
    RETURNS text
    LANGUAGE sql
    IMMUTABLE
    AS $$
      SELECT coalesce(a, b)
    $$
    """,
]


def _backend_root():
    return Path(__file__).resolve().parent.parent


def _apply_env_file(path):
    if not path.is_file():
        return
    text = path.read_text(encoding="utf-8-sig")
    for raw in text.splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        if line.lower().startswith("export "):
            line = line[7:].strip()
        key, _, value = line.partition("=")
        key = key.strip()
        value = value.strip()
        if len(value) >= 2 and value[0] == value[-1] and value[0] in "\"'":
            value = value[1:-1]
        if key and key not in os.environ:
            os.environ[key] = value


def load_env_files():
    backend = _backend_root()
    repo = backend.parent
    for path in (repo / ".env", backend / ".env"):
        _apply_env_file(path)


def fold_text(value):
    text = "" if value is None else str(value)
    text = re.sub(r"[\u200b-\u200d\ufeff]", "", text)
    text = unicodedata.normalize("NFKC", text)
    text = unicodedata.normalize("NFD", text)
    text = "".join(ch for ch in text if unicodedata.category(ch) != "Mn")
    text = text.replace("Đ", "D").replace("đ", "d")
    return text.strip().lower()


def compact_text(value):
    return re.sub(r"[^a-z0-9]+", "", fold_text(value))


def adapt_sql(sql):
    return str(sql).replace("BEGIN IMMEDIATE", "BEGIN").replace("?", "%s")


def _adapt_value(value):
    if isinstance(value, datetime):
        if value.tzinfo is None:
            value = value.replace(tzinfo=timezone.utc)
        return value.astimezone(timezone.utc).isoformat().replace("+00:00", "Z")
    return value


class CompatRow(dict):
    def __getitem__(self, key):
        if isinstance(key, int):
            return list(self.values())[key]
        return super().__getitem__(key)


def adapt_row(row):
    if row is None:
        return None
    if isinstance(row, CompatRow):
        return row
    return CompatRow((key, _adapt_value(value)) for key, value in dict(row).items())


class Cursor:
    def __init__(self, cur):
        self._cur = cur
        self.lastrowid = None

    def fetchone(self):
        return adapt_row(self._cur.fetchone())

    def fetchall(self):
        return [adapt_row(row) for row in self._cur.fetchall()]

    def __iter__(self):
        for row in self._cur:
            yield adapt_row(row)

    @property
    def rowcount(self):
        return self._cur.rowcount


def _affected(count, fallback=0):
    if count is None or count < 0:
        return fallback
    return count


class Database:
    def __init__(self, conn):
        self._conn = conn
        self.total_changes = 0

    def execute(self, sql, params=None):
        sql = adapt_sql(sql)
        if params is None:
            cur = self._conn.execute(sql)
        else:
            if isinstance(params, list):
                params = tuple(params)
            cur = self._conn.execute(sql, params)
        self.total_changes += _affected(cur.rowcount)
        return Cursor(cur)

    def executemany(self, sql, seq_of_params):
        rows = list(seq_of_params)
        sql = adapt_sql(sql)
        with self._conn.cursor() as cur:
            cur.executemany(sql, rows)
            self.total_changes += _affected(cur.rowcount, len(rows))
        return self

    def commit(self):
        self._conn.execute("COMMIT")

    def rollback(self):
        self._conn.execute("ROLLBACK")

    def close(self):
        self._conn.close()


def _env(key, default=""):
    value = os.environ.get(key)
    if value is None:
        return default
    return str(value).strip()


def _missing_db_fields_error():
    return RuntimeError(
        "Thieu thong tin PostgreSQL. Dat trong backend/.env, vi du:\n"
        "DB_HOST=127.0.0.1\n"
        "DB_PORT=5432\n"
        "DB_USERNAME=postgres\n"
        "DB_PASSWORD=postgres\n"
        "DB_NAME=order_management\n"
        "DB_NAME_TEST=order_management_test"
    )


def format_db_target(settings):
    settings = settings or {}
    host = settings.get("host") or ""
    port = settings.get("port") or 5432
    dbname = settings.get("dbname") or ""
    user = settings.get("user") or ""
    return f"{user}@{host}:{port}/{dbname}"


def _db_settings_from_mapping(raw):
    return {
        "host": str(raw.get("host") or "").strip(),
        "port": int(raw.get("port") or 5432),
        "user": str(raw.get("user") or "").strip(),
        "password": str(raw.get("password") or ""),
        "dbname": str(raw.get("dbname") or "").strip(),
        "sslmode": str(raw.get("sslmode") or "disable").strip() or "disable",
    }


def resolve_db_settings(config=None, testing=False):
    load_env_files()
    if config is None and has_app_context():
        config = current_app.config
    config = config or {}
    stored = config.get("DATABASE")
    if isinstance(stored, dict) and stored.get("host") and stored.get("dbname"):
        settings = _db_settings_from_mapping(stored)
        if not settings.get("user"):
            raise _missing_db_fields_error()
        return settings
    settings = {
        "host": _env("DB_HOST"),
        "port": int(_env("DB_PORT", "5432") or 5432),
        "user": _env("DB_USERNAME") or _env("DB_USER"),
        "password": _env("DB_PASSWORD"),
        "dbname": _env("DB_NAME"),
        "sslmode": _env("DB_SSLMODE", "disable") or "disable",
    }
    if testing:
        test_name = str(config.get("DB_NAME_TEST") or _env("DB_NAME_TEST") or "").strip()
        if not test_name:
            raise RuntimeError(
                "Thieu DB_NAME_TEST. Dat trong backend/.env, vi du:\n"
                "DB_NAME_TEST=order_management_test"
            )
        if test_name == settings.get("dbname"):
            raise RuntimeError("DB_NAME_TEST khong duoc trung DB_NAME.")
        settings["dbname"] = test_name
    if not settings.get("host") or not settings.get("user") or not settings.get("dbname"):
        raise _missing_db_fields_error()
    return settings


_IDENT = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")


def _connect(settings, dbname=None):
    return psycopg.connect(
        host=settings["host"],
        port=settings["port"],
        user=settings["user"],
        password=settings["password"],
        dbname=dbname or settings["dbname"],
        sslmode=settings["sslmode"],
        row_factory=dict_row,
        autocommit=True,
        connect_timeout=5,
    )


def _connect_error():
    return RuntimeError(
        "Khong ket noi duoc PostgreSQL. Kiem tra DB_HOST/DB_USERNAME/DB_PASSWORD/DB_NAME trong backend/.env"
    )


def _ensure_database(settings):
    dbname = settings["dbname"]
    if not _IDENT.fullmatch(dbname):
        raise RuntimeError(f"Ten database khong hop le: {dbname}")
    try:
        return _connect(settings)
    except psycopg.OperationalError as exc:
        message = str(exc)
        missing = f'database "{dbname}"' in message and "does not exist" in message
        if not missing:
            raise _connect_error() from exc
        try:
            with _connect(settings, dbname="postgres") as admin:
                row = admin.execute(
                    "SELECT 1 AS ok FROM pg_database WHERE datname = %s",
                    (dbname,),
                ).fetchone()
                if not row:
                    admin.execute(
                        f"CREATE DATABASE {dbname} ENCODING 'UTF8' TEMPLATE template0"
                    )
        except psycopg.OperationalError as create_exc:
            raise _connect_error() from create_exc
        try:
            return _connect(settings)
        except psycopg.OperationalError as retry_exc:
            raise _connect_error() from retry_exc


def get_db():
    if "db" not in g:
        settings = resolve_db_settings()
        conn = _ensure_database(settings)
        conn.execute("SET TIME ZONE 'UTC'")
        conn.execute("SET client_encoding TO 'UTF8'")
        g.db = Database(conn)
    return g.db


def close_db(_error=None):
    conn = g.pop("db", None)
    if conn is not None:
        conn.close()


def table_columns(db, table):
    rows = db.execute(
        """
        SELECT column_name
        FROM information_schema.columns
        WHERE table_schema = current_schema() AND table_name = ?
        """,
        (table,),
    ).fetchall()
    return {row["column_name"] for row in rows}


def ensure_columns(db, table, columns):
    existing = table_columns(db, table)
    for name, coltype in columns:
        if name not in existing:
            db.execute(f"ALTER TABLE {table} ADD COLUMN IF NOT EXISTS {name} {coltype}")


def init_schema(conn=None):
    db = conn or get_db()
    for statement in SQL_FUNCTIONS:
        db.execute(statement)
    for statement in SCHEMA_STATEMENTS:
        db.execute(statement)
    ensure_columns(db, "emp", (("pbb", "TEXT"), ("pba", "TEXT")))


def reset_tables(conn=None):
    db = conn or get_db()
    db.execute("TRUNCATE oders, config, emp, process RESTART IDENTITY CASCADE")


@contextmanager
def transaction():
    db = get_db()
    db.execute("BEGIN")
    try:
        yield db
        db.execute("COMMIT")
    except Exception:
        try:
            db.execute("ROLLBACK")
        except Exception:
            pass
        raise


def row_dict(row):
    if row is None:
        return None
    return dict(row)


def parse_data(raw):
    if not raw:
        return {}
    if isinstance(raw, dict):
        return raw
    try:
        value = json.loads(raw)
    except (TypeError, json.JSONDecodeError):
        return {}
    return value if isinstance(value, dict) else {}


def dump_data(value):
    payload = value if isinstance(value, dict) else {}
    return Jsonb(payload)


def placeholders(count):
    return ",".join("?" * count)


def batched(items, size=BIND_LIMIT):
    seq = list(items)
    for start in range(0, len(seq), size):
        yield seq[start : start + size]
